version: '0.0.2'
source: "https://github.com/tr7zw/ProcessedModTemplate/tree/stonecutter"
replacements:
  name: "WaveyCapes"
  id: "waveycapes"
  version: "1.8.1"
  description: "The cape shouldn't be a static slab!"
  homepageUrl: "https://modrinth.com/mod/wavey-capes"
  sourcesUrl: "https://github.com/tr7zw/WaveyCapes"
  issuesUrl: "https://github.com/tr7zw/WaveyCapes/issues"
  fabric_entrypoint: "dev.tr7zw.waveycapes.WaveyCapesMod"
  fabric_modmenu_entrypoint: "dev.tr7zw.waveycapes.WaveyCapesModMenu"
  relocationpackage: "dev.tr7zw.waveycapes"
  modrinthid: kYuIpRLv
  curseforgeid: 521594
  versionlessname: "WCVersionless"
  fabric_dependencies: "
      modCompileOnly 'curse.maven:morebanners-515000:4575797'\n
      modCompileOnly 'maven.modrinth:ears:1.4.6+fabric-1.20.2'\n
      modCompileOnly 'maven.modrinth:playeranimator:1.0.2-rc1+1.20.4-fabric'\n
      modCompileOnly 'curse.maven:minecraftcapes-mod-359836:4763650'\n
      modCompileOnly 'maven.modrinth:shoulder-surfing-reloaded:MCDpnF47'\n
      "
  forge_dependencies: "
      modCompileOnly 'curse.maven:minecraftcapes-mod-359836:4562670'\n
      modCompileOnly 'maven.modrinth:playeranimator:1.0.2-rc1+1.20.4-forge'\n
      modCompileOnly 'maven.modrinth:ears:1.4.6+fabric-1.20.2'\n
      modCompileOnly 'maven.modrinth:shoulder-surfing-reloaded:ZAtuVliv'\n
      "
  neoforge_dependencies: "
      if (stonecutter.eval(\"${project.minecraft_version}\", \"<= 1.21.10\")) {\n
      modCompileOnly 'curse.maven:minecraftcapes-mod-359836:4562670'\n
      } else {\n
      modCompileOnly 'curse.maven:minecraftcapes-mod-359836:7318376'\n
      }\n
      modCompileOnly 'maven.modrinth:playeranimator:1.0.2-rc1+1.20.4-forge'\n
      modCompileOnly 'maven.modrinth:ears:1.4.6+fabric-1.20.2'\n
      modCompileOnly 'maven.modrinth:shoulder-surfing-reloaded:DKEyLO9H'\n
      "
enabledFlags:
  - autopublish
  - publishFabric
  - publishForge
  - publishNeo
  - modrinth
  - curseforge
  - versionless
  - includeLibs
  - addTRenderLib
  - addTRansitionLib
rootProject:
  template: "."
subProjects:
  WCVersionless:
    template: "Versionless"
    replacements:
      dependencies: '
      compileOnly "com.google.code.gson:gson:2.10.1"

      compileOnly "org.apache.logging.log4j:log4j-core:2.20.0"
      '